"""add scan records table

Revision ID: f287a408ca67
Revises: da1ae5cbd5f2
Create Date: 2026-09-13 18:28:07.786981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f287a408ca67'
down_revision = 'da1ae5cbd5f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scan_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=500), nullable=False),
    sa.Column('species_prediction', sa.String(length=200), nullable=True),
    sa.Column('species_confidence', sa.Float(), nullable=True),
    sa.Column('top_3_fallback', sa.JSON(), nullable=True),
    sa.Column('is_healthy', sa.Boolean(), nullable=True),
    sa.Column('disease_name', sa.String(length=200), nullable=True),
    sa.Column('disease_confidence', sa.Float(), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('gradcam_image_path', sa.String(length=500), nullable=True),
    sa.Column('growth_stage', sa.String(length=100), nullable=True),
    sa.Column('recommendations', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scan_records')
    # ### end Alembic commands ###
